name:  Build Debian Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
        - run: npm install
        - run: npm run build

        - name: Deploy app
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: releases
            FOLDER: release
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}